M48
; DRILL file {KiCad 8.0.4} date 2024-08-22T18:58:12-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-22T18:58:12-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X2.8391Y-2.4721
X3.0666Y-2.4721
T2
X2.6773Y-2.3048
X2.6773Y-2.797
X3.2285Y-2.797
M30
